apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-src-sample-vol
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /Users/Shared/k8s/2.src-deploy-disk/storage